# SPDX-FileCopyrightText: 2025 The Orthros Developers
#
# SPDX-License-Identifier: AGPL-3.0-only

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "07:00"
      timezone: "Europe/London"
    commit-message:
      prefix: "chore(ci-deps)"
    reviewers:
      - "shymega"
    groups:
      gh-actions-deps:
        patterns:
          - "*"
