# SPDX-FileCopyrightText: 2025 The Orthros Developers
#
# SPDX-License-Identifier: AGPL-3.0-only

pull_request_rules:
  - name: Automatic merge for Dependabot pull requests or Flake updates
    conditions:
      - or:
          - author=github-actions[bot]
          - author=dependabot[bot]
      - base=main
    actions:
      queue:
        method: merge
        priority: high

  - name: Automatic update to the main branch for pull requests
    conditions:
      - -conflict # skip PRs with conflicts
      - -draft # skip GH draft PRs
      - -author=dependabot[bot] # skip dependabot PRs
    actions:
      update:
  - name: Delete head branch on merged pull requests
    conditions:
      - merged
    actions:
      delete_head_branch:
