# SPDX-FileCopyrightText: 2025 The Orthros Developers
#
# SPDX-License-Identifier: AGPL-3.0-only

[workspace]
members = [
  "crates/bin/*",
  "crates/lib/*",
]
default-members = [
  "crates/bin/*",
  "crates/lib/*"
]
resolver = "2"
